server:
  port: 8081
  servlet:
    session:
      cookie:
        secure: true
        SameSite: None
    encoding:
      force: true
      enabled: true
      charset: UTF-8
spring:
  profiles:
    active: local
  application:
    name: back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD:123}
    url: jdbc:mysql://localhost:3306/komeiji?serverTimezone=UTC
    username: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-wait: -1ms
          max-active: 16
  mail:
    host: smtp.gmail.com
    port: 587
    username: komeiji.cyou@gmail.com
    password: jmjccsiynvxbpehx
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


swagger:
