server:
  port: 8081
  servlet:
    session:
      cookie:
        secure: true
        SameSite: None
    encoding:
      force: true
      enabled: true
      charset: UTF-8
spring:
  profiles:
    active: local
  application:
    name: back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD:123}
    url: jdbc:mysql://localhost:3306/komeiji?serverTimezone=UTC
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    path match:
      matching-strategy: ant_path_matcher

swagger:
